In [2]:
import numpy as np
import matplotlib.pyplot as plt



# Folha 7

## Exercicio 2 
(sugestao do professor nao começar pelo exercicio 1
)

In [ ]:
def QR(A):
    rows = len(A)
    cols = len()
    A1 = np.matrix(np.zeros((N,N)))
    Q = np.matrix(np.zeros((N,N)))
    R = np.matrix(np.zeros((N,N)))
    A1[:,0] = A[:,0]
    Q[:,0] = A1[:,0]/(np.linalg.norm(A1[:,0]))
    for i in range(1,N):
        A1[:,i] = A[:,i] - (np.dot(np.matrix.transpose(Q[:,k]),A[:,i])for k in range(i))*Q[:,i]
        Q[:,i] = A1[:,i]/(np.linalg.norm(A1[:,i]))
        for j in range(i,N):
            R[i,j] = 



In [17]:
def QR(A):
    rows, cols = A.shape[0],A.shape[1]
    print(rows,cols)
    Q = np.zeros((rows,cols))
    R = np.zeros((cols,cols))
    for i in range(cols):
        if i == 0:
            fator = A[:,0]
        else:
            vetorsub = Q[:,:i] @ R[:i,i]
            fator = A[:,i] - vetorsub
            
        Q[:,i] = fator/np.linalg.norm(fator)
        for j in range(i,cols):
            if j == i:
                R[j,j] = np.linalg.norm(fator)
            else:
                R[i,j] = np.dot(np.transpose(Q[:,i]),A[:,j])
            
    
    return Q, R

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(QR(A))
print(np.linalg.qr(A))

3 2
(array([[ 0.16903085,  0.89708523],
       [ 0.50709255,  0.27602622],
       [ 0.84515425, -0.34503278]]), array([[5.91607978, 7.43735744],
       [0.        , 0.82807867]]))
QRResult(Q=array([[-0.16903085,  0.89708523],
       [-0.50709255,  0.27602622],
       [-0.84515425, -0.34503278]]), R=array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867]]))


In [6]:
A = np.matrix(np.zeros((16,15)))
i = 17
print(A[:,:i])
print(A.shape[1])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
15
