In [5]:
import numpy as np
import matplotlib.pyplot as plt 

## Regra dos Quadrados

In [ ]:
PESQUISAR MELHOR DEPOIS PQ NAO ENCONTREI NA NET DIZ 
QUE É MESMO QUE A REGRA DO TRAPEZIO

## Regra do trapezio

In [ ]:
def trapezio(a,b,N):
    h = (b-a)/N
    integral = 0
    for k in range(1,N):
        integral += f(a+k*h)
    integral += 1/2 * (f(a) + f(b))
    return h*integral 
def f(x):
    return x**2 
print(trapezio(0,1,100))

#Acho que esta correto Preciso confirmar com o Sr. GPT

0.33335000000000004


## Regra de Simpson

In [18]:
def simpson(a,b,N):
    h = (b-a)/N
    integral = f(a)+f(b)
    for kodd in range(1,N,2):
        integral += 4*(f(a + kodd*h))
    for keven in range(2,N,2):
        integral += 2*(f(a + keven*h))
    
    return (h/3)* integral 

print(simpson(0,1,6))


0.3333333333333333


## Erros no integral de trapezio

In [33]:
def errotrapezio(a, b, epsilon):
    N = 2
    h = (b-a)/N
    integral1 = (h/2)*(f(a)+f(b))
    erro = 1
    while erro > epsilon:
        N += 2
        h = (b-a)/N
        integral2 = (f(a)+f(b))/2
        for k in range(1,N):
            integral2 += f(a+k*h)
        integral2 *= h
        erro = abs(integral2 - integral1)
        integral1 = integral2
    return print(f"Conseguimos a integral: {integral1} com um erro de {erro} e com {N} divisoes")
print(errotrapezio(0,1,1e-7))

Conseguimos a integral: 0.4558155353133534 com um erro de 9.982528231811116e-08 e com 684 divisoes
None


In [31]:
def f(x):
    return((np.sin(np.sqrt(100*x))**2))
print(errotrapezio(0,1,1e-6))

Conseguimos a integral: 0.45575392316737184 com um erro de 9.977348722767232e-07 e com 318 divisoes
None


## Erro no integral de Simpson 

In [ ]:
def simpson(a,b,epsilon):
    erro = 1
    N = 2
    h = (b-a)/N
    Integral1 = (h/3)*(f(a) + f(b))
    while erro > epsilon:
        print("Entrei aqui")
        N += 2
        h = (b-a)/N
        Integral2 = (f(a)+f(b))
        for kodd in range(1,N,2):
            Integral2 += 4*f(a + kodd*h)
        for keven in range(2,N,2):
            Integral2 += 2*f(a+keven*h)
        Integral2 *= (h/3)
        erro = abs(Integral2 - Integral1)/15
        Integral1 = Integral2
    return print(f"Conseguimos a integral: {Integral1} com um erro de {erro} e com {N} divisoes")

print(simpson(0,1,1e-6))


[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

## Metodo de Romberg




In [51]:
def metodoRomberg(a, b, max, epsilon):
    R = np.zeros((max,max))
    N = 1
    h = (b-a)/N
    x=np.linspace(a,b,N+1)
    integral1 = (h/2)*(f(a)+f(b))
    erro = 1
    R[0][0] = integral1
    print("integral1", integral1)


    for i in range(1,max):
        N *= 2
        h = (b-a)/N
        x = np.linspace(a, b, N+1)
        R[i][0] = 1/2 * R[i-1][0] + h*(np.sum(f(x[1:N:2]))) 
        print("aqui",R[i][0])
        for j in range(1,i+1):
            erro = (1/(4**(j)-1)) * (R[i][j-1]-R[i-1][j-1])
            print("erro", erro)
            R[i][j] = R[i][j-1] + erro 
    
            if abs(erro)<epsilon:
                return R[i][j]
    
    return R[max-1][max-1]

def f(x):
    return x**3 + np.exp(-2*x)

a=0
b=1
max = 10 
epsilon=1e-7

print(metodoRomberg(a,b,max,epsilon))

integral1 1.0676676416183064
aqui 0.7802735413948744
erro -0.09579803340781068
aqui 0.706926975662703
erro -0.024448855244057117
erro -0.00013315917122785532
aqui 0.6884879973467334
erro -0.006146326105323211
erro -9.096611815710235e-06
erro -1.9661298132611814e-07
aqui 0.6838717070974469
erro -0.0015387634164288158
erro -5.818373594701498e-07
erro -3.377554537640849e-09
0.6823323584661041


## Erro no Metodo de Romberg ele ja faz isso automaticamente nao é preciso, talvez fazer o romberg de simpson, mas é pior que o romberg normal

## Quadratura Gaussiana

In [62]:
A = np.array([[1, 4, 8, 4],
              [4, 2, 3, 7],
              [8, 3, 6, 9],
              [4, 7, 9, 2]], float)
print(A[0,:])
A[1,:] -= A[0,:]*A[1,0]
print(A)

[1. 4. 8. 4.]
[[  1.   4.   8.   4.]
 [  0. -14. -29.  -9.]
 [  8.   3.   6.   9.]
 [  4.   7.   9.   2.]]


In [ ]:
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
C = np.copy(A)
v = np.array([5,0,5,0])

def gaussian_elimination(A,v):
    C = np.copy(A)
    b = np.copy(v)
    N = len(C)
    for i in range(N):
        pivot = C[i,i]
        C[i,:] /= pivot
        b[i] /= pivot
        for j in range(i+1,N):
            fator = C[j,i]
            C[j,:] = C[j,:] - C[i,:]*fator
            b[j] = b[j]-b[i]*fator
    #Agora fazer o backsubstitution
    x = np.empty(N,float)
    for k in range(N-1,-1,-1):
        x[k] = b[k]
        for i in range(k+1,N):
            x[k] -= C[k,i]*x[i]
    
    return x

print(gaussian_elimination(A,v))

[6.51315789 1.05263158 1.         0.        ]


In [116]:
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)

v = np.array([5, 0, 5, 0], float)
print(len(v))
def gaussian_elimination(A, v):
    A = A.copy()
    v = v.copy()
    N = len(A)

    for i in range(N):
        pivot = A[i, i]
        if pivot == 0:
            raise ValueError("Pivot zero encontrado — necessário pivotamento parcial.")
        
        for j in range(i+1, N):
            fator = A[j, i] / pivot
            A[j, :] -= fator * A[i, :]
            v[j] -= fator * v[i]
    return v

print(gaussian_elimination(A,v))

4
[5.         1.25       6.31578947 4.61538462]


## Erro na Quadratura Gaussiana

## Derivadas

## Solução de Sistemas Lineares

## Eliminação Gaussiana com Backsusbstitution

## Elimnação gaussiana com pivotagem 

## Decomposição LU 

## Decomposição LU com pivotagem

## INVERSA DA MATRIZ

## Matriz tridiagonal

## EigenValues and EigenVectors

## Metodos de Relaxação