In [2]:
import numpy as np
import matplotlib as plt


In [3]:
#Gauss elimination

A =

SyntaxError: invalid syntax (1416227191.py, line 3)

In [ ]:
#QR algorithm with eigenvalues

import numpy as np

def qr_decomposition_modified(A):
    N = len(A)
    Q = np.zeros((N, N))
    R = np.zeros((N, N))
    V = np.copy(A)

    for i in range(N):
        R[i,i] = np.linalg.norm(V[:,i])
        Q[:,i] = V[:,i] / R[i,i]
        for j in range(i+1, N):
            R[i,j] = np.dot(Q[:,i], V[:,j])
            V[:,j] = V[:,j] - R[i,j] * Q[:,i]

    return Q, R

def qr_algorithm(A, tol=1e-6, max_iterations=1000):
    A_k = np.copy(A)

    for iteration in range(max_iterations):
        Q, R = qr_decomposition_modified(A_k)
        A_k = R @ Q

        off_diagonal = A_k - np.diag(np.diag(A_k))
        if np.all(np.abs(off_diagonal) < tol):
            print(f"\nConvergiu em {iteration} iterações")
            break

    eigenvalues = np.diag(A_k)
    return eigenvalues, A_k

# Teste
A = np.array([[1, 4, 8, 4],
              [4, 2, 3, 7],
              [8, 3, 6, 9],
              [4, 7, 9, 2]], float)

eigenvalues, A_final = qr_algorithm(A)

print("\nAutovalores encontrados:")
print(eigenvalues)

print("\nMatriz final aproximada (quase diagonal):")
print(A_final)



Convergiu em 17 iterações

Autovalores encontrados:
[21. -8. -3.  1.]

Matriz final aproximada (quase diagonal):
[[ 2.10000000e+01  7.36068000e-07  3.45152416e-14 -2.16976381e-14]
 [ 7.36067998e-07 -8.00000000e+00  5.99038979e-08  8.85107004e-15]
 [ 1.76373367e-14  5.99038974e-08 -3.00000000e+00 -2.06493955e-08]
 [ 5.69063112e-23  9.58659066e-16 -2.06493983e-08  1.00000000e+00]]


In [ ]:
def autovalores(A, iterações):
    An = np.copy(A)
    for i in range(iterações):
        Q,R = qr_decomposition_modified(An)
        An = R@Q
    return np.diag(An)
print(autovalores(A,1000))

[21. -8. -3.  1.]


In [ ]:
#Gaussian Quadrature 

def gaussxw(N):

    # Initial approximation to roots of the Legendre polynomial
    a = np.linspace(3,4*N-1,N)/(4*N+2)
    x = np.cos(np.pi*a+1/(8*N*N*np.tan(a)))

    # Find roots using Newton's method
    epsilon = 1e-15
    delta = 1.0
    while delta>epsilon:
        p0 = np.ones(N,float)
        p1 = np.copy(x)
        for k in range(1,N):
            p0,p1 = p1,((2*k+1)*x*p1-k*p0)/(k+1)
        dp = (N+1)*(p0-x*p1)/(1-x*x)
        dx = p1/dp
        x -= dx
        delta = max(abs(dx))

    # Calculate the weights
    w = 2*(N+1)*(N+1)/(N*N*(1-x*x)*dp*dp)

    return x,w

def gaussxwab(N,a,b):
    x,w = gaussxw(N)
    return 0.5*(b-a)*x+0.5*(b+a),0.5*(b-a)*w

In [ ]:
def gauss(A,v):
    N = len(A)
    x = np.copy(v)
    
    for i in range(N):
        div = A[i,i]
        A[i,:] /= A[i,i]
        v[i] /= A[i,i]

        for j in range(i+1,N):
            mult = A[j,i]
            A[j,:] -= mult*A[i,:]
            v[j] -= mult*v[i]
    
    #backsubstitution

    for i in range(N-1,-1,-1):
        for j in range(i+1,N):
            x[i] -= A[i,j]*x[j]
    return x

print()

In [ ]:
import numpy as np

A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
b = np.array([5, 0, 5, 0], float)
n = len(b)
print(A[1])

[-1.  5.  0. -1.]


In [ ]:

A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
C = np.copy(A)
b = np.array([5, 0, 5, 0], float)
n = len(b)
B = np.eye(n)
for i in range(n):
    pivot = A[i,i]
    A[i] = A[i] / pivot
    B[i] = B[i] / pivot
    b[i] = b[i] / pivot
    for j in range(n):
        if j != i:
            fator = A[j,i]
            A[j] -= fator * A[i]
            B[j] -= fator * B[i]
            b[j] -= fator * b[i]

print(b)


[2.65517241 0.86206897 3.10344828 1.65517241]


In [ ]:
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
b = np.array([5, 0, 5, 0], float)

n = len(A)
I = np.eye(n)
for i in range(n):
    A[i] /= A[i, i]
    I[i] /= A[i, i]
    for j in range(n):
        if j != i:
            fator = A[j, i]
            A[j] -= fator * A[i]
            I[j] -= fator * I[i]
print(B[j])

[0.15862069 0.10344828 0.17241379 0.35862069]


In [ ]:
#Gauss jordan
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
C = np.copy(A)
b = np.array([5, 0, 5, 0], float)
n = len(A)
I = np.eye(n)

for i in range(n):
    pivot = A[i,i]
    print(A)
    A[i,:] /= pivot
    I[i,:] /= pivot
    
    for j in range(n):
        if j != i:
            fator = A[j,i]
            A[j,:] -= fator * A[i,:]
            I[j,:] -= fator * I[i]

print(C@I)
print(A)



[[ 4. -1. -1. -1.]
 [-1.  5.  0. -1.]
 [-1.  0.  3. -1.]
 [-1. -1. -1.  4.]]
[[ 1.   -0.25 -0.25 -0.25]
 [ 0.    4.75 -0.25 -1.25]
 [ 0.   -0.25  2.75 -1.25]
 [ 0.   -1.25 -1.25  3.75]]
[[ 1.          0.         -0.26315789 -0.31578947]
 [ 0.          1.         -0.05263158 -0.26315789]
 [ 0.          0.          2.73684211 -1.31578947]
 [ 0.          0.         -1.31578947  3.42105263]]
[[ 1.          0.          0.         -0.44230769]
 [ 0.          1.          0.         -0.28846154]
 [ 0.          0.          1.         -0.48076923]
 [ 0.          0.          0.          2.78846154]]
[[ 1.00000000e+00 -4.16333634e-17  0.00000000e+00 -5.55111512e-17]
 [-2.77555756e-17  1.00000000e+00 -2.77555756e-17 -5.55111512e-17]
 [ 2.77555756e-17  1.38777878e-17  1.00000000e+00  5.55111512e-17]
 [ 1.11022302e-16  5.55111512e-17  0.00000000e+00  1.00000000e+00]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
C = np.copy(A)
b = np.array([5, 0, 5, 0], float)
n = len(A)
I = np.eye(n)


for i in range(n):
    div = A[i,i]
    A[i] /= div
    I[i] /= div
    b[i] /= div

    for j in range(n):
        if j != i:
            fator = A[j,i]
            A[j] -= fator*A[i]
            I[j] -= fator * I[i]
            b[j] -= fator* b[i]

print(C@I)

print(b)
        

[[ 1.00000000e+00 -4.16333634e-17  0.00000000e+00 -5.55111512e-17]
 [-2.77555756e-17  1.00000000e+00 -2.77555756e-17 -5.55111512e-17]
 [ 2.77555756e-17  1.38777878e-17  1.00000000e+00  5.55111512e-17]
 [ 1.11022302e-16  5.55111512e-17  0.00000000e+00  1.00000000e+00]]
[2.65517241 0.86206897 3.10344828 1.65517241]


In [11]:
import numpy as np
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
C = np.copy(A)
b = np.array([5, 0, 5, 0], float)
n = len(A)
I = np.eye(n)


for i in range(n):
    div = A[i,i]
    A[i] /= div
    b[i] /= div
    
    for j in range(i):
        fator = A[j,i]
        A[j] -= fator*A[i]
        b[i] -= fator*b[i]

#backsubstitution
x = np.copy(b)
for i in range(n,-1,-1):
    for j in range(i,n):
        x[i] -= A[j,i] * x[j] 

print(x)



[0.36241319 0.01446759 0.17361111 0.        ]


In [ ]:
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
b = np.array([5, 0, 5, 0], float)
n = len(A)
U = np.zeros((n,n))
L = np.zeros((n,n))

for i in range(n):
    for j in range(i,n):
        U[i,j] = A[i,j] - sum(L[i,k]*U[k,j] for k in range(i))
    
    for j in range(i+1,n):
        L[j,i] = A[j,i] - sum((L[j,k]*U[k,i] for k in range(i))) / U[i,i]

        Ux = y Ly = v
np.linagl.solve 

In [ ]:
import numpy as np

def qr_decomposition_modified(A):
    N = len(A)
    Q = np.zeros((N, N))
    R = np.zeros((N, N))
    V = np.copy(A)

    for i in range(N):
        R[i,i] = np.linalg.norm(V[:,i])
        Q[:,i] = V[:,i] / R[i,i]
        for j in range(i+1, N):
            R[i,j] = np.dot(Q[:,i], V[:,j])
            V[:,j] = V[:,j] - R[i,j] * Q[:,i]

    return Q, R

def qr_algorithm(A, tol=1e-6, max_iterations=1000):
    A_k = np.copy(A)

    for iteration in range(max_iterations):
        Q, R = qr_decomposition_modified(A_k)
        A_k = R @ Q

        off_diagonal = A_k - np.diag(np.diag(A_k))
        if np.all(np.abs(off_diagonal) < tol):
            print(f"\nConvergiu em {iteration} iterações")
            break

    eigenvalues = np.diag(A_k)
    return eigenvalues, A_k

# Teste
A = np.array([[1, 4, 8, 4],
              [4, 2, 3, 7],
              [8, 3, 6, 9],
              [4, 7, 9, 2]], float)

eigenvalues, A_final = qr_algorithm(A)

print("\nAutovalores encontrados:")
print(eigenvalues)


print("\nMatriz final aproximada (quase diagonal):")
print(A_final)



Convergiu em 17 iterações

Autovalores encontrados:
[21. -8. -3.  1.]

Matriz final aproximada (quase diagonal):
[[ 2.10000000e+01  7.36068000e-07  3.45152416e-14 -2.16976381e-14]
 [ 7.36067998e-07 -8.00000000e+00  5.99038979e-08  8.85107004e-15]
 [ 1.76373367e-14  5.99038974e-08 -3.00000000e+00 -2.06493955e-08]
 [ 5.69063112e-23  9.58659066e-16 -2.06493983e-08  1.00000000e+00]]


: 

In [ ]:
 for i in range(N):
        R[i,i] = np.linalg.norm(V[:,i])
        Q[:,i] = V[:,i] / R[i,i]
        for j in range(i+1, N):
            R[i,j] = np.dot(Q[:,i], V[:,j])
            V[:,j] = V[:,j] - R[i,j] * Q[:,i]

R[i,i] = norma de a1
Q[:,i] = v1/R[i,i]
    for j in range(i+1,N)


#Q é uma matriz com as linhas sendo o vetor u dividido pela sua norma
#R é uma matriz com as diagonais sendo a norma de u E os demais componentes sendo o produto vetorial dado por np.dot(qi*aj) com j sendo de i+1 ate n
ui = ai - R[i,j]*Q[:,i]
#PARA ENCONTRAR AUTOVALORES BASTA FAZER
#ENCONTRAR A MATRIZ QR = A 
#FAZER UMA NOVA MATRIZ A1 = RQ 