In [2]:
#vimos eliminação de gauss e gaussjordan
#sendo a elim. de gauss é melhor
#elim. de gauss aplicada à uma matriz para construir a inversa 
from numpy import array,empty

A = array([[ 4,  -1,  -1,  -1 ],
           [ -1,  3, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ -1, -1,  -1,  4 ]],float)
v = array([ 5, 0, 5, 0 ],float)
N = len(v)

# Gaussian elimination
for m in range(N):

    # Divide by the diagonal element
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div

    # Now subtract from the lower rows
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Backsubstitution
x = empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)




[3.         1.66666667 3.33333333 2.        ]


In [3]:
#Tentar fazer pivotagem 


from numpy import array,empty

A = array([[ 2,  6,  6],
           [ 6,  3, 6],
           [ 6, 6, 2]],float)
v = array([4, 8, 2], float) 
N = len(v)

# Gaussian elimination
for m in range(N):

    # Divide by the diagonal element

    div = A[m,m]
    if m == 2:
        print(A)
        print("vantes:",v)
   
    A[m,:] /= div
    v[m] /= div
    if m == 2:
        print(A)
        print("v:",v)
   
    # Now subtract from the lower rows
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Backsubstitution
x = empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]
print(x)


[[ 1.   3.   3. ]
 [-0.   1.   0.8]
 [ 0.   0.  -6.4]]
vantes: [ 2.          0.26666667 -6.8       ]
[[ 1.   3.   3. ]
 [-0.   1.   0.8]
 [-0.  -0.   1. ]]
v: [2.         0.26666667 1.0625    ]
[ 0.5625     -0.58333333  1.0625    ]


In [4]:
import numpy as np

A = np.array([[ 4,  -1,  -1,  -1 ],
           [ -1,  3, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ -1, -1,  -1,  4 ]],float)
v = np.array([ 5, 0, 5, 0 ],float)
N = len(v)

for m in range(N): #Estamos a dividr cada linha pelo elemento diagonal da linha por exemplo linha 1 / a11 linha 2/a22 e etc
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div

    for i in range(m+1, N): #Estamos a subtrair cada linha pelo elemento m = 0 i = 0 a00 = 4 linha0 - a00 multiplicado pela linha 0 
        mult = A[i,m] #Entao o que estamos a fazer é subtrair as linhas 0,1,2,3 respectivamnete pelos elementos a00linha0,a11linha0,a22linha0,a33linha0
        A [i,:] -= mult*A[m,:] #e depois fazemos o mesmo em v 23  
        v[i] -= mult*v[m] #faz o mesmo com o vetor resultado
    
    
x = np.empty(N,float)# cria uma matriz de mesmo tamanho que v
for m in range(N-1,-1,-1):#range que começa no penultimo elemento da matriz ate chegar 
    x[m] = v[m]
    for i in range(m+1, N):
        x[m] -= A[m,i]*x[i]

print(x)

[3.         1.66666667 3.33333333 2.        ]


In [ ]:
#fiz esse 


import numpy as np

A = np.array([[ 4,  -1,  -1,  -1 ],
           [ -1,  3, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ -1, -1,  -1,  4 ]],float)
v = np.array([ 5, 0, 5, 0 ],float)
N = len(v)
B = np.copy(A)
u = np.copy(v)

for m in range(N):
    B = np.copy(A)
    linha = m
    bigger = abs(A[m,m])
    for s in range(m+1, N):
        if abs(A[s,m]) > bigger:
            linha = s
            bigger = abs(A[s,m])
            print("bigger alterado", bigger)
    A[[m,linha]] = A[[linha,m]]
    v[[m,linha]] = v[[linha,m]]
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div
    

    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]
x = np.empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)

print(A)

    

[3.         1.66666667 3.33333333 2.        ]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          1.         -0.5       ]
 [ 0.          0.          0.          1.        ]]


In [6]:
A = np.array([[ 4,  -1,  -1,  -1 ],
           [ -1,  3, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ 5, -1,  -1,  4 ]],float)
v = np.array([ 5, 0, 5, 0 ],float)
N = len(v)

A[[0,1]] = A[[1,0]]
print(A)

[[-1.  3.  0. -1.]
 [ 4. -1. -1. -1.]
 [-1.  0.  3. -1.]
 [ 5. -1. -1.  4.]]


In [24]:
import numpy as np

A = np.array([[ 4,  -1,  -1,  -1 ],
           [ -1,  0, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ -1, -1,  -1,  4 ]],float)
v = np.array([ 5, 0, 5, 0 ],float)
N = len(v)
B = np.copy(A)
u = np.copy(v)

for m in range(N):
    B = np.copy(A)
    linha = m
    bigger = abs(A[m,m])
    for s in range(m+1, N):
        if abs(A[s,m]) > bigger:
            linha = s
            bigger = abs(A[s,m])
            print("bigger alterado", bigger)
    A[[m,linha]] = A[[linha,m]]
    v[[m,linha]] = v[[linha,m]]
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div


    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]


print(A)



bigger alterado 1.25
[[ 1.         -0.25       -0.25       -0.25      ]
 [-0.          1.          1.         -3.        ]
 [ 0.          0.          1.         -0.66666667]
 [-0.         -0.         -0.          1.        ]]


In [ ]:
A = np.array([[ 4,  -1,  -1,  -1 ],
           [ -1,  3, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ -1, -1,  -1,  4 ]],float)
v = np.array([ 5, 0, 5, 0 ],float)
N = len(v)

U = np.zeros((N,N))
L = np.zeros((N,N))
#Uij = aij - sum(Lik *ukj ) sendo o j para o U de i ate n
#Lji = aji - sum(Ljk * Uki ) sendo o j para o L de i+1 ate n

for i in range(N):
    for j in range(i,N):
        U[i,j] = A[i,j] - sum(L[i,k]*U[k,j] for k in range(i))
        U[i,j] = A[i,j] - sum(L[i,k]*U[k,j] for k in range(i))
    L[i,i] = 1
    for j in range(i+1,N):
        L[j,i] = (A[j,i] - sum(L[j,k]*U[k,i] for k in range(i))) / U[i,i]
        
#Backsubstitution:
y = np.copy(v)
#To find y

for i in range(N):
    y[i] -= sum(L[i,k]*y[k] for k in range(i))
    
      
        

#To find x:
x = np.copy(y)
x[N-1] = y[N-1]/U[N-1,N-1]
for i in range(N-2,-1,-1):
    x[i] -= sum((U[i,k]*x[k]) for k in range(i+1,N))
    x[i] /= U[i,i]

print(x)

#Agora é fazer o backsubstitution sabendo que ux = y e Ly = v
U[i,j] = A[i,j] - sum((U[k,j]*L[i,k]))#range(i,n)
L[j,i] = A[j,i] - sum((U[k,i]*L[j,k]))#range(i+1,n)
backsubstitution de ux = y ly = v queroemos enconrar x 

[3.         1.66666667 3.33333333 2.        ]


In [9]:
A = np.array([[ 1/1000 + 1/2000 +j*10**(9),  -j*10**(9),  0],
           [ -j*10**(9),  1/2000 + 1/1000 + j*10**(9)+j, 0.5*10**(9)],
           [ 0, -j*10**(9), 1/1000 +1/2000+j*0.5*10**(9)]],dtype=complex)
v = np.array([ 3/1000, 3/2000,  3/1000],complex)
N = len(v)
print(len(v))
print(N)
U = np.zeros((N,N),complex)
L = np.zeros((N,N),complex)


for i in range(N):
    for j in range(i,N):
        U[i,j] = A[i,j] - sum(L[i,k]*U[k,j] for k in range(i))
        
    L[i,i] = 1
    for j in range(i+1,N):
        L[j,i] = (A[j,i] - sum(L[j,k]*U[k,i] for k in range(i))) / U[i,i]
        
#Backsubstitution:
y = np.copy(v)
#To find y

for i in range(N):
    y[i] -= sum(L[i,k]*y[k] for k in range(i))
    
      
        

#To find x:
x = np.copy(y)
x[N-1] = y[N-1]/U[N-1,N-1]
for i in range(N-2,-1,-1):
    x[i] -= sum((U[i,k]*x[k]) for k in range(i+1,N))
    x[i] /= U[i,i]

print(x)
print(np.linalg.solve(A,v))

3
3
[4.50000014e-12+0.j 3.50000014e-12+0.j 8.99999998e-12+0.j]
[4.49999999e-12+0.j 3.49999999e-12+0.j 8.99999998e-12+0.j]


In [10]:
A = np.array([[ 4,  -1,  -1,  -1 ],
           [ -1,  3, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ -1, -1,  -1,  4 ]],float)
v = np.array([ 5, 0, 5, 0 ],float)
N = len(v)

L = np.zeros(N)
U = np.zeros(N)

for i in range(N):
    for j in range(i+1)

SyntaxError: expected ':' (690638100.py, line 12)

In [ ]:
import numpy as np
A = np.array([[ 4,  -1,  -1,  -1 ],
           [ -1,  3, 0, -1 ],
           [ -1, 0, 3,  -1 ],
           [ -1, -1,  -1,  4 ]],float)

v = np.array([ 5, 0, 5, 0 ],float)
N = len(v)


SyntaxError: invalid syntax (4168016690.py, line 9)

In [ ]:
import numpy as np

A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  0,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
v = np.array([5, 0, 5, 0], float)
N = len(v)

# Guardar a ordem das variáveis (já que vamos trocar colunas)
ordem = np.arange(N)

for m in range(N):
    # Procurar o maior elemento da submatriz A[m:,m:]
    maior = 0
    linha = m
    coluna = m
    for i in range(m, N):
        for j in range(m, N):
            if abs(A[i,j]) > maior:
                maior = abs(A[i,j])
                linha = i
                coluna = j
    
    # Trocar linhas
    A[[m, linha]] = A[[linha, m]]
    v[[m, linha]] = v[[linha, m]]
    
    # Trocar colunas (e registrar que trocamos)
    A[:, [m, coluna]] = A[:, [coluna, m]]
    ordem[[m, coluna]] = ordem[[coluna, m]]
    
    # Dividir a linha m pelo pivô
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div
    
    # Eliminação
    for i in range(m+1, N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

print("Matriz A escalonada:")
print(A)
print("Vetor v escalonado:")
print(v)
print("Ordem das variáveis após pivotagem:")
print(ordem)


In [ ]:
def eliminacao_gauss(A, b):
    n = len(A)
    for i in range(n):
        for j in range(i+1, n):
            fator = A[j,i] / A[i,i]
            A[j,i:] -= fator * A[i,i:]
            b[j] -= fator * b[i]
    x = np.zeros(n)
    for i in reversed(range(n)):
        x[i] = (b[i] - np.dot(A[i,i+1:], x[i+1:])) / A[i,i]
    return x

# Exemplo
A = np.array([[2,1,-1],[-3,-1,2],[-2,1,2]], dtype=float)
b = np.array([8,-11,-3], dtype=float)
print(eliminacao_gauss(A, b))


In [ ]:
def gauss_jordan(A, b):
    n = len(A)
    for i in range(n):
        A[i] = A[i] / A[i,i]
        b[i] = b[i] / A[i,i]
        for j in range(n):
            if j != i:
                fator = A[j,i]
                A[j] -= fator * A[i]
                b[j] -= fator * b[i]
    return b

# Exemplo
A = np.array([[2,1,-1],[-3,-1,2],[-2,1,2]], dtype=float)
b = np.array([8,-11,-3], dtype=float)
print(gauss_jordan(A, b))


In [ ]:
import numpy as np

A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
b = np.array([5, 0, 5, 0], float)
n = len(v)
for i in range(n):
    for i in range(n):
        A[i] = A[i] / A[i,i]
        b[i] = b[i] / A[i,i]
        for j in range(n):
            if j != i:
                fator = A[j,i]
                A[j] -= fator * A[i]
                b[j] -= fator * b[i]

print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
b = np.array([5, 0, 5, 0], float)

n = len(A)

for i in range(n):
    for j in range(i+1, n):
        fator = A[j,i] / A[i,i]
        A[j,i:] -= fator * A[i,i:]
        b[j] -= fator * b[i]

        

print(A)

[[ 4.         -1.         -1.         -1.        ]
 [ 0.          4.75       -0.25       -1.25      ]
 [ 0.          0.          2.73684211 -1.31578947]
 [ 0.          0.          0.          2.78846154]]


In [ ]:
def inversa_matriz(A):
    A = np.array(A, dtype=float)
    a

In [ ]:
A = np.array([[ 4,  -1,  -1,  -1 ],
              [ -1,  5,  0,  -1 ],
              [ -1,  0,  3,  -1 ],
              [ -1, -1, -1,  4 ]], float)
n = len(A)
I = np.eye(n)
for i in range(n):
    A[i] /= A[i, i]
    I[i] /= A[i, i]
    for j in range(n):
        if j != i:
            fator = A[j, i]
            A[j] -= fator * A[i]
            I[j] -= fator * I[i]



print((A))



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


: 